import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <section>
      <h2>Homepage</h2>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nobis quibusdam sunt consequatur hic, eveniet unde
        dicta quia, architecto fugiat fugit, ratione quas vel! Eum corrupti esse iusto sapiente quos. Lorem ipsum dolor
        sit amet consectetur adipisicing elit. Libero harum natus, ex suscipit aliquam incidunt quia. Optio quia
        necessitatibus, saepe recusandae quod culpa vel, corrupti accusantium voluptatibus voluptates quae neque. Lorem
        ipsum dolor sit amet consectetur adipisicing elit. Hic minima autem quisquam veritatis provident nihil, dolores
        nemo ullam fugiat eum vitae, totam illo modi obcaecati repudiandae saepe iusto perferendis adipisci. Lorem ipsum
        dolor sit amet consectetur adipisicing elit. Ad nobis quibusdam sunt consequatur hic, eveniet unde dicta quia,
        architecto fugiat fugit, ratione quas vel! Eum corrupti esse iusto sapiente quos. Lorem ipsum dolor sit amet
        consectetur adipisicing elit. Libero harum natus, ex suscipit aliquam incidunt quia. Optio quia necessitatibus,
        saepe recusandae quod culpa vel, corrupti accusantium voluptatibus voluptates quae neque. Lorem ipsum dolor sit
        amet consectetur adipisicing elit. Hic minima autem quisquam veritatis provident nihil, dolores nemo ullam
        fugiat eum vitae, totam illo modi obcaecati repudiandae saepe iusto perferendis adipisci. Lorem ipsum dolor sit
        amet consectetur adipisicing elit. Ad nobis quibusdam sunt consequatur hic, eveniet unde dicta quia, architecto
        fugiat fugit, ratione quas vel! Eum corrupti esse iusto sapiente quos. Lorem ipsum dolor sit amet consectetur
        adipisicing elit. Libero harum natus, ex suscipit aliquam incidunt quia. Optio quia necessitatibus, saepe
        recusandae quod culpa vel, corrupti accusantium voluptatibus voluptates quae neque. Lorem ipsum dolor sit amet
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nobis quibusdam sunt consequatur hic, eveniet unde
        dicta quia, architecto fugiat fugit, ratione quas vel! Eum corrupti esse iusto sapiente quos. Lorem ipsum dolor
        sit amet consectetur adipisicing elit. Libero harum natus, ex suscipit aliquam incidunt quia. Optio quia
        necessitatibus, saepe recusandae quod culpa vel, corrupti accusantium voluptatibus voluptates quae neque. Lorem
        ipsum dolor sit amet consectetur adipisicing elit. Hic minima autem quisquam veritatis provident nihil, dolores
        nemo ullam fugiat eum vitae, totam illo modi obcaecati repudiandae saepe iusto perferendis adipisci. Lorem ipsum
        dolor sit amet consectetur adipisicing elit. Ad nobis quibusdam sunt consequatur hic, eveniet unde dicta quia,
        architecto fugiat fugit, ratione quas vel! Eum corrupti esse iusto sapiente quos. Lorem ipsum dolor sit amet
        consectetur adipisicing elit. Libero harum natus, ex suscipit aliquam incidunt quia. Optio quia necessitatibus,
        saepe recusandae quod culpa vel, corrupti accusantium voluptatibus voluptates quae neque. Lorem ipsum dolor sit
        amet consectetur adipisicing elit. Hic minima autem quisquam veritatis provident nihil, dolores nemo ullam
        fugiat eum vitae, totam illo modi obcaecati repudiandae saepe iusto perferendis adipisci. Lorem ipsum dolor sit
        amet consectetur adipisicing elit. Ad nobis quibusdam sunt consequatur hic, eveniet unde dicta quia, architecto
        fugiat fugit, ratione quas vel! Eum corrupti esse iusto sapiente quos. Lorem ipsum dolor sit amet consectetur
        adipisicing elit. Libero harum natus, ex suscipit aliquam incidunt quia. Optio quia necessitatibus, saepe
        recusandae quod culpa vel, corrupti accusantium voluptatibus voluptates quae neque. Lorem ipsum dolor sit amet
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nobis quibusdam sunt consequatur hic, eveniet unde
        dicta quia, architecto fugiat fugit, ratione quas vel! Eum corrupti esse iusto sapiente quos. Lorem ipsum dolor
        sit amet consectetur adipisicing elit. Libero harum natus, ex suscipit aliquam incidunt quia. Optio quia
        necessitatibus, saepe recusandae quod culpa vel, corrupti accusantium voluptatibus voluptates quae neque. Lorem
        ipsum dolor sit amet consectetur adipisicing elit. Hic minima autem quisquam veritatis provident nihil, dolores
        nemo ullam fugiat eum vitae, totam illo modi obcaecati repudiandae saepe iusto perferendis adipisci. Lorem ipsum
        dolor sit amet consectetur adipisicing elit. Ad nobis quibusdam sunt consequatur hic, eveniet unde dicta quia,
        architecto fugiat fugit, ratione quas vel! Eum corrupti esse iusto sapiente quos. Lorem ipsum dolor sit amet
        consectetur adipisicing elit.
      </p>
    </section>
  );
}
